#include "ActorTypeNames.h"

extern "C" {
#include "battle/actor_types.h"
}

const std::vector<ActorTypeName> gActorTypeNames = {
    { "Red Goomba", ACTOR_TYPE_RED_GOOMBA, false },
    { "Red Paragoomba", ACTOR_TYPE_RED_PARAGOOMBA, false },
    { "Gloomba", ACTOR_TYPE_GLOOMBA, false },
    { "Paragloomba", ACTOR_TYPE_PARAGLOOMBA, false },
    { "Spiked Gloomba", ACTOR_TYPE_SPIKED_GLOOMBA, false },
    { "Dark Koopa", ACTOR_TYPE_DARK_KOOPA, false },
    { "Dark Paratroopa", ACTOR_TYPE_DARK_PARATROOPA, false },
    { "Goomba", ACTOR_TYPE_GOOMBA, false },
    { "Paragoomba", ACTOR_TYPE_PARAGOOMBA, false },
    { "Spiked Goomba", ACTOR_TYPE_SPIKED_GOOMBA, false },
    { "Fuzzy", ACTOR_TYPE_FUZZY, false },
    { "Koopa Troopa", ACTOR_TYPE_KOOPA_TROOPA, false },
    { "Paratroopa", ACTOR_TYPE_PARATROOPA, false },
    { "Bob-omb", ACTOR_TYPE_BOB_OMB, false },
    { "Bob-omb Dup", ACTOR_TYPE_BOB_OMB_DUP, true },
    { "Bullet Bill", ACTOR_TYPE_BULLET_BILL, false },
    { "Bill Blaster", ACTOR_TYPE_BILL_BLASTER, false },
    { "Cleft", ACTOR_TYPE_CLEFT, false },
    { "Monty Mole", ACTOR_TYPE_MONTY_MOLE, false },
    { "Bandit", ACTOR_TYPE_BANDIT, false },
    { "Pokey", ACTOR_TYPE_POKEY, false },
    { "Pokey Mummy", ACTOR_TYPE_POKEY_MUMMY, false },
    { "Swooper", ACTOR_TYPE_SWOOPER, false },
    { "Buzzy Beetle", ACTOR_TYPE_BUZZY_BEETLE, false },
    { "Stone Chomp", ACTOR_TYPE_STONE_CHOMP, false },
    { "Piranha Plant", ACTOR_TYPE_PIRANHA_PLANT, false },
    { "Forest Fuzzy", ACTOR_TYPE_FOREST_FUZZY, false },
    { "Hyper Goomba", ACTOR_TYPE_HYPER_GOOMBA, false },
    { "Hyper Paragoomba", ACTOR_TYPE_HYPER_PARAGOOMBA, false },
    { "Hyper Cleft", ACTOR_TYPE_HYPER_CLEFT, false },
    { "Clubba", ACTOR_TYPE_CLUBBA, false },
    { "Shy Guy", ACTOR_TYPE_SHY_GUY, false },
    { "Groove Guy", ACTOR_TYPE_GROOVE_GUY, false },
    { "Sky Guy", ACTOR_TYPE_SKY_GUY, false },
    { "Medi Guy", ACTOR_TYPE_MEDI_GUY, false },
    { "Pyro Guy", ACTOR_TYPE_PYRO_GUY, false },
    { "Spy Guy", ACTOR_TYPE_SPY_GUY, false },
    { "Fuzzipede", ACTOR_TYPE_FUZZIPEDE, false },
    { "Hurt Plant", ACTOR_TYPE_HURT_PLANT, false },
    { "M. Bush", ACTOR_TYPE_M_BUSH, false },
    { "Aqua Fuzzy", ACTOR_TYPE_AQUA_FUZZY, false },
    { "Jungle Fuzzy", ACTOR_TYPE_JUNGLE_FUZZY, false },
    { "Spear Guy", ACTOR_TYPE_SPEAR_GUY, false },
    { "Lava Bubble", ACTOR_TYPE_LAVA_BUBBLE, false },
    { "Spike Top", ACTOR_TYPE_SPIKE_TOP, false },
    { "Putrid Piranha", ACTOR_TYPE_PUTRID_PIRANHA, false },
    { "Lakitu", ACTOR_TYPE_LAKITU, false },
    { "Spiny", ACTOR_TYPE_SPINY, false },
    { "Monty Mole Boss", ACTOR_TYPE_MONTY_MOLE_BOSS, false },
    { "Bzzap!", ACTOR_TYPE_BZZAP, false },
    { "Crazee Dayzee", ACTOR_TYPE_CRAZEE_DAYZEE, false },
    { "Amazy Dayzee", ACTOR_TYPE_AMAZY_DAYZEE, false },
    { "Ruff Puff", ACTOR_TYPE_RUFF_PUFF, false },
    { "Spike", ACTOR_TYPE_SPIKE, false },
    { "Gulpit", ACTOR_TYPE_GULPIT, false },
    { "Gulpit Rocks", ACTOR_TYPE_GULPIT_ROCKS, false },
    { "White Clubba", ACTOR_TYPE_WHITE_CLUBBA, false },
    { "Frost Piranha", ACTOR_TYPE_FROST_PIRANHA, false },
    { "Swoopula", ACTOR_TYPE_SWOOPULA, false },
    { "Duplighost", ACTOR_TYPE_DUPLIGHOST, false },
    { "Ghost Goombario", ACTOR_TYPE_GHOST_GOOMBARIO, false },
    { "Ghost Kooper", ACTOR_TYPE_GHOST_KOOPER, false },
    { "Ghost Bombette", ACTOR_TYPE_GHOST_BOMBETTE, false },
    { "Ghost Parakarry", ACTOR_TYPE_GHOST_PARAKARRY, false },
    { "Ghost Bow", ACTOR_TYPE_GHOST_BOW, false },
    { "Ghost Watt", ACTOR_TYPE_GHOST_WATT, false },
    { "Ghost Sushie", ACTOR_TYPE_GHOST_SUSHIE, false },
    { "Ghost Lakilester", ACTOR_TYPE_GHOST_LAKILESTER, false },
    { "Albino Dino", ACTOR_TYPE_ALBINO_DINO, false },
    { "Ember", ACTOR_TYPE_EMBER, false },
    { "Bony Beetle", ACTOR_TYPE_BONY_BEETLE, false },
    { "Dry Bones", ACTOR_TYPE_DRY_BONES, false },
    { "Dry Bones 2", ACTOR_TYPE_DRY_BONES2, false },
    { "Bombshell Blaster", ACTOR_TYPE_BOMBSHELL_BLASTER, false },
    { "Bombshell Bill", ACTOR_TYPE_BOMBSHELL_BILL, false },
    { "Hammer Bros", ACTOR_TYPE_HAMMER_BROS, false },
    { "Koopatrol", ACTOR_TYPE_KOOPATROL, false },
    { "Magikoopa", ACTOR_TYPE_MAGIKOOPA, false },
    { "Flying Magikoopa", ACTOR_TYPE_FLYING_MAGIKOOPA, false },
    { "Magiclone", ACTOR_TYPE_MAGICLONE, false },
    { "Flying Magiclone", ACTOR_TYPE_FLYING_MAGICLONE, false },
    { "Red Magikoopa", ACTOR_TYPE_RED_MAGIKOOPA, false },
    { "Flying Red Magikoopa", ACTOR_TYPE_FLYING_RED_MAGIKOOPA, false },
    { "Green Magikoopa", ACTOR_TYPE_GREEN_MAGIKOOPA, false },
    { "Flying Green Magikoopa", ACTOR_TYPE_FLYING_GREEN_MAGIKOOPA, false },
    { "Yellow Magikoopa", ACTOR_TYPE_YELLOW_MAGIKOOPA, false },
    { "Flying Yellow Magikoopa", ACTOR_TYPE_FLYING_YELLOW_MAGIKOOPA, false },
    { "Gray Magikoopa", ACTOR_TYPE_GRAY_MAGIKOOPA, false },
    { "Flying Gray Magikoopa", ACTOR_TYPE_FLYING_GRAY_MAGIKOOPA, false },
    { "White Magikoopa", ACTOR_TYPE_WHITE_MAGIKOOPA, false },
    { "Flying White Magikoopa", ACTOR_TYPE_FLYING_WHITE_MAGIKOOPA, false },
    { "Unused", ACTOR_TYPE_UNUSED_5B, true },
    { "Unused", ACTOR_TYPE_UNUSED_5C, true },
    { "Unused", ACTOR_TYPE_UNUSED_5D, true },
    { "Unused", ACTOR_TYPE_UNUSED_5E, true },
    { "Unused", ACTOR_TYPE_UNUSED_5F, true },
    { "Unused", ACTOR_TYPE_UNUSED_60, true },
    { "Unused", ACTOR_TYPE_UNUSED_61, true },
    { "Unused", ACTOR_TYPE_UNUSED_62, true },
    { "Unused", ACTOR_TYPE_UNUSED_63, true },
    { "Unused", ACTOR_TYPE_UNUSED_64, true },
    { "Unused", ACTOR_TYPE_UNUSED_65, true },
    { "Unused", ACTOR_TYPE_UNUSED_66, true },
    { "Unused", ACTOR_TYPE_UNUSED_67, true },
    { "Unused", ACTOR_TYPE_UNUSED_68, true },
    { "Unused", ACTOR_TYPE_UNUSED_69, true },
    { "Unused", ACTOR_TYPE_UNUSED_6A, true },
    { "Monty Hole", ACTOR_TYPE_MONTY_HOLE, false },
    { "Unused", ACTOR_TYPE_UNUSED_6C, true },
    { "Unused", ACTOR_TYPE_UNUSED_6D, true },
    { "Player", ACTOR_TYPE_PLAYER, false },
    { "Goombario", ACTOR_TYPE_GOOMBARIO, false },
    { "Kooper", ACTOR_TYPE_KOOPER, false },
    { "Bombette", ACTOR_TYPE_BOMBETTE, false },
    { "Parakarry", ACTOR_TYPE_PARAKARRY, false },
    { "Bow", ACTOR_TYPE_BOW, false },
    { "Watt", ACTOR_TYPE_WATT, false },
    { "Sushie", ACTOR_TYPE_SUSHIE, false },
    { "Lakilester", ACTOR_TYPE_LAKILESTER, false },
    { "Twink", ACTOR_TYPE_TWINK, false },
    { "Unused", ACTOR_TYPE_UNUSED_78, true },
    { "Unused", ACTOR_TYPE_UNUSED_79, true },
    { "The Master 1", ACTOR_TYPE_THE_MASTER_1, false },
    { "The Master 2", ACTOR_TYPE_THE_MASTER_2, false },
    { "The Master 3", ACTOR_TYPE_THE_MASTER_3, false },
    { "Chan", ACTOR_TYPE_CHAN, false },
    { "Lee", ACTOR_TYPE_LEE, false },
    { "Lee Goombario", ACTOR_TYPE_LEE_GOOMBARIO, false },
    { "Lee Kooper", ACTOR_TYPE_LEE_KOOPER, false },
    { "Lee Bombette", ACTOR_TYPE_LEE_BOMBETTE, false },
    { "Lee Parakarry", ACTOR_TYPE_LEE_PARAKARRY, false },
    { "Lee Bow", ACTOR_TYPE_LEE_BOW, false },
    { "Lee Watt", ACTOR_TYPE_LEE_WATT, false },
    { "Lee Sushie", ACTOR_TYPE_LEE_SUSHIE, false },
    { "Lee Lakilester", ACTOR_TYPE_LEE_LAKILESTER, false },
    { "Kammy Koopa", ACTOR_TYPE_KAMMY_KOOPA, false },
    { "Jr. Troopa 1", ACTOR_TYPE_JR_TROOPA_1, false },
    { "Jr. Troopa 2", ACTOR_TYPE_JR_TROOPA_2, false },
    { "Jr. Troopa 3", ACTOR_TYPE_JR_TROOPA_3, false },
    { "Jr. Troopa 4", ACTOR_TYPE_JR_TROOPA_4, false },
    { "Jr. Troopa 5", ACTOR_TYPE_JR_TROOPA_5, false },
    { "Jr. Troopa 6", ACTOR_TYPE_JR_TROOPA_6, false },
    { "Jr. Troopa Dup 1", ACTOR_TYPE_JR_TROOPA_DUP1, true },
    { "Jr. Troopa Dup 2", ACTOR_TYPE_JR_TROOPA_DUP2, true },
    { "Blue Goomba Boss", ACTOR_TYPE_BLUE_GOOMBA_BOSS, false },
    { "Red Goomba Boss", ACTOR_TYPE_RED_GOOMBA_BOSS, false },
    { "Goomba King", ACTOR_TYPE_GOOMBA_KING, false },
    { "Goomnut Tree", ACTOR_TYPE_GOOMNUT_TREE, false },
    { "Goombario Tutor 1", ACTOR_TYPE_GOOMBARIO_TUTOR1, false },
    { "Magikoopa Boss", ACTOR_TYPE_MAGIKOOPA_BOSS, false },
    { "Flying Magikoopa Boss", ACTOR_TYPE_FLYING_MAGIKOOPA_BOSS, false },
    { "Magikoopa Dup 1", ACTOR_TYPE_MAGIKOOPA_DUP1, true },
    { "Magikoopa Dup 2", ACTOR_TYPE_MAGIKOOPA_DUP2, true },
    { "Fake Bowser", ACTOR_TYPE_FAKE_BOWSER, false },
    { "Koopa Bros", ACTOR_TYPE_KOOPA_BROS, false },
    { "Green Ninjakoopa", ACTOR_TYPE_GREEN_NINJAKOOPA, false },
    { "Red Ninjakoopa", ACTOR_TYPE_RED_NINJAKOOPA, false },
    { "Black Ninjakoopa", ACTOR_TYPE_BLACK_NINJAKOOPA, false },
    { "Yellow Ninjakoopa", ACTOR_TYPE_YELLOW_NINJAKOOPA, false },
    { "Eldstar", ACTOR_TYPE_ELDSTAR, false },
    { "Buzzar", ACTOR_TYPE_BUZZAR, false },
    { "Tutankoopa", ACTOR_TYPE_TUTANKOOPA, false },
    { "Chomp", ACTOR_TYPE_CHOMP, false },
    { "Tubba Blubba Invincible", ACTOR_TYPE_TUBBA_BLUBBA_INVINCIBLE, false },
    { "Tubba Blubba", ACTOR_TYPE_TUBBA_BLUBBA, false },
    { "Tubba Heart", ACTOR_TYPE_TUBBA_HEART, false },
    { "Stilt Guy", ACTOR_TYPE_STILT_GUY, false },
    { "Shy Stack", ACTOR_TYPE_SHY_STACK, false },
    { "Shy Squad", ACTOR_TYPE_SHY_SQUAD, false },
    { "General Guy", ACTOR_TYPE_GENERAL_GUY, false },
    { "Toy Tank", ACTOR_TYPE_TOY_TANK, false },
    { "Light Bulb", ACTOR_TYPE_LIGHT_BULB, false },
    { "Signal Guy", ACTOR_TYPE_SIGNAL_GUY, false },
    { "Shy Squad Redux", ACTOR_TYPE_SHY_SQUAD_REDUX, false },
    { "Shy Squad Stub", ACTOR_TYPE_SHY_SQUAD_STUB, true },
    { "Anti Guy (Toy Box)", ACTOR_TYPE_ANTI_GUY_OMO, false },
    { "Anti Guy (Bowser's Castle)", ACTOR_TYPE_ANTI_GUY_KPA, false },
    { "Big Lantern Ghost", ACTOR_TYPE_BIG_LANTERN_GHOST, false },
    { "Goomba King Dup", ACTOR_TYPE_GOOMBA_KING_DUP, true },
    { "Lava Piranha Phase 1", ACTOR_TYPE_LAVA_PIRANHA_PHASE_1, false },
    { "Lava Piranha Phase 2", ACTOR_TYPE_LAVA_PIRANHA_PHASE_2, false },
    { "Lava Bud Phase 1", ACTOR_TYPE_LAVA_BUD_PHASE_1, false },
    { "Lava Bud Phase 2", ACTOR_TYPE_LAVA_BUD_PHASE_2, false },
    { "Petit Piranha", ACTOR_TYPE_PETIT_PIRANHA, false },
    { "Petit Piranha Bomb", ACTOR_TYPE_PETIT_PIRANHA_BOMB, false },
    { "Kent C. Koopa", ACTOR_TYPE_KENT_C_KOOPA, false },
    { "Huff N. Puff", ACTOR_TYPE_HUFF_N_PUFF, false },
    { "Tuff Puff", ACTOR_TYPE_TUFF_PUFF, false },
    { "Monstar", ACTOR_TYPE_MONSTAR, false },
    { "Crystal King", ACTOR_TYPE_CRYSTAL_KING, false },
    { "Crystal Clone", ACTOR_TYPE_CRYSTAL_CLONE, false },
    { "Crystal Bit", ACTOR_TYPE_CRYSTAL_BIT, false },
    { "Intro Bowser", ACTOR_TYPE_INTRO_BOWSER, false },
    { "Hallway Bowser", ACTOR_TYPE_HALLWAY_BOWSER, false },
    { "Hallway Bowser Dup", ACTOR_TYPE_HALLWAY_BOWSER_DUP, true },
    { "Final Bowser 1", ACTOR_TYPE_FINAL_BOWSER_1, false },
    { "Final Bowser 1 Dup", ACTOR_TYPE_FINAL_BOWSER_1_DUP, true },
    { "Final Bowser 2", ACTOR_TYPE_FINAL_BOWSER_2, false },
    { "Final Bowser 2 Dup", ACTOR_TYPE_FINAL_BOWSER_2_DUP, true },
    { "Blooper", ACTOR_TYPE_BLOOPER, false },
    { "Electro Blooper 1", ACTOR_TYPE_ELECTRO_BLOOPER1, false },
    { "Electro Blooper 2", ACTOR_TYPE_ELECTRO_BLOOPER2, false },
    { "Super Blooper 1", ACTOR_TYPE_SUPER_BLOOPER1, false },
    { "Super Blooper 2", ACTOR_TYPE_SUPER_BLOOPER2, false },
    { "Blooper Baby", ACTOR_TYPE_BLOOPER_BABY, false },
    { "Lakilester Dup", ACTOR_TYPE_LAKILESTER_DUP, true },
    { "Slot Machine Start", ACTOR_TYPE_SLOT_MACHINE_START, false },
    { "Slot Machine Stop", ACTOR_TYPE_SLOT_MACHINE_STOP, false },
    { "Whacka", ACTOR_TYPE_WHACKA, false },
    { "Slot Machine Start Dup 1", ACTOR_TYPE_SLOT_MACHINE_START_DUP1, true },
    { "Slot Machine Start Dup 2", ACTOR_TYPE_SLOT_MACHINE_START_DUP2, true },
    { "Slot Machine Start Dup 3", ACTOR_TYPE_SLOT_MACHINE_START_DUP3, true },
};

const char* ActorTypeNames_Get(int32_t actorType) {
    for (const ActorTypeName& entry : gActorTypeNames) {
        if (entry.actorType == actorType) {
            return entry.name;
        }
    }
    return nullptr;
}
