#pragma once
// Auto-generated by tools/gen-smash-bridges-yaml.py
// OTR asset path symbols for dgb_01 smash bridges vertex data

#include "alignment.h"
#include "ultra64.h"

static const ALIGN_ASSET(2) char _vtx_C20F40_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C20F40.vtx";
#define vtx_C20F40 ((Vtx*) _vtx_C20F40_path)
static const ALIGN_ASSET(2) char _vtx_C21100_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C21100.vtx";
#define vtx_C21100 ((Vtx*) _vtx_C21100_path)
static const ALIGN_ASSET(2) char _vtx_C21130_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C21130.vtx";
#define vtx_C21130 ((Vtx*) _vtx_C21130_path)
static const ALIGN_ASSET(2) char _vtx_C211E0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C211E0.vtx";
#define vtx_C211E0 ((Vtx*) _vtx_C211E0_path)
static const ALIGN_ASSET(2) char _vtx_C211F0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C211F0.vtx";
#define vtx_C211F0 ((Vtx*) _vtx_C211F0_path)
static const ALIGN_ASSET(2) char _vtx_C21240_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C21240.vtx";
#define vtx_C21240 ((Vtx*) _vtx_C21240_path)
static const ALIGN_ASSET(2) char _vtx_C21360_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C21360.vtx";
#define vtx_C21360 ((Vtx*) _vtx_C21360_path)
static const ALIGN_ASSET(2) char _vtx_C213C0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C213C0.vtx";
#define vtx_C213C0 ((Vtx*) _vtx_C213C0_path)
static const ALIGN_ASSET(2) char _vtx_C215A0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C215A0.vtx";
#define vtx_C215A0 ((Vtx*) _vtx_C215A0_path)
static const ALIGN_ASSET(2) char _vtx_C21700_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C21700.vtx";
#define vtx_C21700 ((Vtx*) _vtx_C21700_path)
static const ALIGN_ASSET(2) char _vtx_C21770_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C21770.vtx";
#define vtx_C21770 ((Vtx*) _vtx_C21770_path)
static const ALIGN_ASSET(2) char _vtx_C21810_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C21810.vtx";
#define vtx_C21810 ((Vtx*) _vtx_C21810_path)
static const ALIGN_ASSET(2) char _vtx_C21930_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C21930.vtx";
#define vtx_C21930 ((Vtx*) _vtx_C21930_path)
static const ALIGN_ASSET(2) char _vtx_C21AE0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C21AE0.vtx";
#define vtx_C21AE0 ((Vtx*) _vtx_C21AE0_path)
static const ALIGN_ASSET(2) char _vtx_C21B20_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C21B20.vtx";
#define vtx_C21B20 ((Vtx*) _vtx_C21B20_path)
static const ALIGN_ASSET(2) char _vtx_C21BD0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C21BD0.vtx";
#define vtx_C21BD0 ((Vtx*) _vtx_C21BD0_path)
static const ALIGN_ASSET(2) char _vtx_C21C90_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C21C90.vtx";
#define vtx_C21C90 ((Vtx*) _vtx_C21C90_path)
static const ALIGN_ASSET(2) char _vtx_C21D30_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C21D30.vtx";
#define vtx_C21D30 ((Vtx*) _vtx_C21D30_path)
static const ALIGN_ASSET(2) char _vtx_C21DD0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C21DD0.vtx";
#define vtx_C21DD0 ((Vtx*) _vtx_C21DD0_path)
static const ALIGN_ASSET(2) char _vtx_C21E00_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C21E00.vtx";
#define vtx_C21E00 ((Vtx*) _vtx_C21E00_path)
static const ALIGN_ASSET(2) char _vtx_C21F30_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C21F30.vtx";
#define vtx_C21F30 ((Vtx*) _vtx_C21F30_path)
static const ALIGN_ASSET(2) char _vtx_C22050_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C22050.vtx";
#define vtx_C22050 ((Vtx*) _vtx_C22050_path)
static const ALIGN_ASSET(2) char _vtx_C22190_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C22190.vtx";
#define vtx_C22190 ((Vtx*) _vtx_C22190_path)
static const ALIGN_ASSET(2) char _vtx_C222D0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C222D0.vtx";
#define vtx_C222D0 ((Vtx*) _vtx_C222D0_path)
static const ALIGN_ASSET(2) char _vtx_C22330_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C22330.vtx";
#define vtx_C22330 ((Vtx*) _vtx_C22330_path)
static const ALIGN_ASSET(2) char _vtx_C224A0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C224A0.vtx";
#define vtx_C224A0 ((Vtx*) _vtx_C224A0_path)
static const ALIGN_ASSET(2) char _vtx_C224E0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C224E0.vtx";
#define vtx_C224E0 ((Vtx*) _vtx_C224E0_path)
static const ALIGN_ASSET(2) char _vtx_C22510_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C22510.vtx";
#define vtx_C22510 ((Vtx*) _vtx_C22510_path)
static const ALIGN_ASSET(2) char _vtx_C22620_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C22620.vtx";
#define vtx_C22620 ((Vtx*) _vtx_C22620_path)
static const ALIGN_ASSET(2) char _vtx_C22780_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C22780.vtx";
#define vtx_C22780 ((Vtx*) _vtx_C22780_path)
static const ALIGN_ASSET(2) char _vtx_C22810_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C22810.vtx";
#define vtx_C22810 ((Vtx*) _vtx_C22810_path)
static const ALIGN_ASSET(2) char _vtx_C22870_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C22870.vtx";
#define vtx_C22870 ((Vtx*) _vtx_C22870_path)
static const ALIGN_ASSET(2) char _vtx_C228F0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C228F0.vtx";
#define vtx_C228F0 ((Vtx*) _vtx_C228F0_path)
static const ALIGN_ASSET(2) char _vtx_C22950_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C22950.vtx";
#define vtx_C22950 ((Vtx*) _vtx_C22950_path)
static const ALIGN_ASSET(2) char _vtx_C229F0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C229F0.vtx";
#define vtx_C229F0 ((Vtx*) _vtx_C229F0_path)
static const ALIGN_ASSET(2) char _vtx_C22B00_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C22B00.vtx";
#define vtx_C22B00 ((Vtx*) _vtx_C22B00_path)
static const ALIGN_ASSET(2) char _vtx_C22C00_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C22C00.vtx";
#define vtx_C22C00 ((Vtx*) _vtx_C22C00_path)
static const ALIGN_ASSET(2) char _vtx_C22E00_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C22E00.vtx";
#define vtx_C22E00 ((Vtx*) _vtx_C22E00_path)
static const ALIGN_ASSET(2) char _vtx_C22EC0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C22EC0.vtx";
#define vtx_C22EC0 ((Vtx*) _vtx_C22EC0_path)
static const ALIGN_ASSET(2) char _vtx_C230A0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C230A0.vtx";
#define vtx_C230A0 ((Vtx*) _vtx_C230A0_path)
static const ALIGN_ASSET(2) char _vtx_C23240_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C23240.vtx";
#define vtx_C23240 ((Vtx*) _vtx_C23240_path)
static const ALIGN_ASSET(2) char _vtx_C23260_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C23260.vtx";
#define vtx_C23260 ((Vtx*) _vtx_C23260_path)
static const ALIGN_ASSET(2) char _vtx_C232A0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C232A0.vtx";
#define vtx_C232A0 ((Vtx*) _vtx_C232A0_path)
static const ALIGN_ASSET(2) char _vtx_C23330_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C23330.vtx";
#define vtx_C23330 ((Vtx*) _vtx_C23330_path)
static const ALIGN_ASSET(2) char _vtx_C233D0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C233D0.vtx";
#define vtx_C233D0 ((Vtx*) _vtx_C233D0_path)
static const ALIGN_ASSET(2) char _vtx_C23480_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C23480.vtx";
#define vtx_C23480 ((Vtx*) _vtx_C23480_path)
static const ALIGN_ASSET(2) char _vtx_C234B0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C234B0.vtx";
#define vtx_C234B0 ((Vtx*) _vtx_C234B0_path)
static const ALIGN_ASSET(2) char _vtx_C235C0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C235C0.vtx";
#define vtx_C235C0 ((Vtx*) _vtx_C235C0_path)
static const ALIGN_ASSET(2) char _vtx_C236E0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C236E0.vtx";
#define vtx_C236E0 ((Vtx*) _vtx_C236E0_path)
static const ALIGN_ASSET(2) char _vtx_C23810_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C23810.vtx";
#define vtx_C23810 ((Vtx*) _vtx_C23810_path)
static const ALIGN_ASSET(2) char _vtx_C238B0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C238B0.vtx";
#define vtx_C238B0 ((Vtx*) _vtx_C238B0_path)
static const ALIGN_ASSET(2) char _vtx_C239D0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C239D0.vtx";
#define vtx_C239D0 ((Vtx*) _vtx_C239D0_path)
static const ALIGN_ASSET(2) char _vtx_C23A70_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C23A70.vtx";
#define vtx_C23A70 ((Vtx*) _vtx_C23A70_path)
static const ALIGN_ASSET(2) char _vtx_C23B70_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C23B70.vtx";
#define vtx_C23B70 ((Vtx*) _vtx_C23B70_path)
static const ALIGN_ASSET(2) char _vtx_C23BA0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C23BA0.vtx";
#define vtx_C23BA0 ((Vtx*) _vtx_C23BA0_path)
static const ALIGN_ASSET(2) char _vtx_C23C70_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C23C70.vtx";
#define vtx_C23C70 ((Vtx*) _vtx_C23C70_path)
static const ALIGN_ASSET(2) char _vtx_C23C90_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C23C90.vtx";
#define vtx_C23C90 ((Vtx*) _vtx_C23C90_path)
static const ALIGN_ASSET(2) char _vtx_C23CE0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C23CE0.vtx";
#define vtx_C23CE0 ((Vtx*) _vtx_C23CE0_path)
static const ALIGN_ASSET(2) char _vtx_C23D20_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C23D20.vtx";
#define vtx_C23D20 ((Vtx*) _vtx_C23D20_path)
static const ALIGN_ASSET(2) char _vtx_C23D60_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C23D60.vtx";
#define vtx_C23D60 ((Vtx*) _vtx_C23D60_path)
static const ALIGN_ASSET(2) char _vtx_C23DD0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C23DD0.vtx";
#define vtx_C23DD0 ((Vtx*) _vtx_C23DD0_path)
static const ALIGN_ASSET(2) char _vtx_C23E00_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C23E00.vtx";
#define vtx_C23E00 ((Vtx*) _vtx_C23E00_path)
static const ALIGN_ASSET(2) char _vtx_C23E20_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C23E20.vtx";
#define vtx_C23E20 ((Vtx*) _vtx_C23E20_path)
static const ALIGN_ASSET(2) char _vtx_C23E50_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C23E50.vtx";
#define vtx_C23E50 ((Vtx*) _vtx_C23E50_path)
static const ALIGN_ASSET(2) char _vtx_C23F10_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C23F10.vtx";
#define vtx_C23F10 ((Vtx*) _vtx_C23F10_path)
static const ALIGN_ASSET(2) char _vtx_C23FD0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C23FD0.vtx";
#define vtx_C23FD0 ((Vtx*) _vtx_C23FD0_path)
static const ALIGN_ASSET(2) char _vtx_C240D0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C240D0.vtx";
#define vtx_C240D0 ((Vtx*) _vtx_C240D0_path)
static const ALIGN_ASSET(2) char _vtx_C241D0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C241D0.vtx";
#define vtx_C241D0 ((Vtx*) _vtx_C241D0_path)
static const ALIGN_ASSET(2) char _vtx_C24350_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C24350.vtx";
#define vtx_C24350 ((Vtx*) _vtx_C24350_path)
static const ALIGN_ASSET(2) char _vtx_C24510_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C24510.vtx";
#define vtx_C24510 ((Vtx*) _vtx_C24510_path)
static const ALIGN_ASSET(2) char _vtx_C24540_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C24540.vtx";
#define vtx_C24540 ((Vtx*) _vtx_C24540_path)
static const ALIGN_ASSET(2) char _vtx_C24600_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C24600.vtx";
#define vtx_C24600 ((Vtx*) _vtx_C24600_path)
static const ALIGN_ASSET(2) char _vtx_C24690_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C24690.vtx";
#define vtx_C24690 ((Vtx*) _vtx_C24690_path)
static const ALIGN_ASSET(2) char _vtx_C24720_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C24720.vtx";
#define vtx_C24720 ((Vtx*) _vtx_C24720_path)
static const ALIGN_ASSET(2) char _vtx_C24730_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C24730.vtx";
#define vtx_C24730 ((Vtx*) _vtx_C24730_path)
static const ALIGN_ASSET(2) char _vtx_C24840_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C24840.vtx";
#define vtx_C24840 ((Vtx*) _vtx_C24840_path)
static const ALIGN_ASSET(2) char _vtx_C24960_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C24960.vtx";
#define vtx_C24960 ((Vtx*) _vtx_C24960_path)
static const ALIGN_ASSET(2) char _vtx_C24980_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C24980.vtx";
#define vtx_C24980 ((Vtx*) _vtx_C24980_path)
static const ALIGN_ASSET(2) char _vtx_C24AD0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C24AD0.vtx";
#define vtx_C24AD0 ((Vtx*) _vtx_C24AD0_path)
static const ALIGN_ASSET(2) char _vtx_C24AF0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C24AF0.vtx";
#define vtx_C24AF0 ((Vtx*) _vtx_C24AF0_path)
static const ALIGN_ASSET(2) char _vtx_C24CD0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C24CD0.vtx";
#define vtx_C24CD0 ((Vtx*) _vtx_C24CD0_path)
static const ALIGN_ASSET(2) char _vtx_C24EB0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C24EB0.vtx";
#define vtx_C24EB0 ((Vtx*) _vtx_C24EB0_path)
static const ALIGN_ASSET(2) char _vtx_C24F30_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C24F30.vtx";
#define vtx_C24F30 ((Vtx*) _vtx_C24F30_path)
static const ALIGN_ASSET(2) char _vtx_C24FB0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C24FB0.vtx";
#define vtx_C24FB0 ((Vtx*) _vtx_C24FB0_path)
static const ALIGN_ASSET(2) char _vtx_C25050_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C25050.vtx";
#define vtx_C25050 ((Vtx*) _vtx_C25050_path)
static const ALIGN_ASSET(2) char _vtx_C25250_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C25250.vtx";
#define vtx_C25250 ((Vtx*) _vtx_C25250_path)
static const ALIGN_ASSET(2) char _vtx_C25310_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C25310.vtx";
#define vtx_C25310 ((Vtx*) _vtx_C25310_path)
static const ALIGN_ASSET(2) char _vtx_C25350_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C25350.vtx";
#define vtx_C25350 ((Vtx*) _vtx_C25350_path)
static const ALIGN_ASSET(2) char _vtx_C25500_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C25500.vtx";
#define vtx_C25500 ((Vtx*) _vtx_C25500_path)
static const ALIGN_ASSET(2) char _vtx_C25600_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C25600.vtx";
#define vtx_C25600 ((Vtx*) _vtx_C25600_path)
static const ALIGN_ASSET(2) char _vtx_C256D0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C256D0.vtx";
#define vtx_C256D0 ((Vtx*) _vtx_C256D0_path)
static const ALIGN_ASSET(2) char _vtx_C25710_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C25710.vtx";
#define vtx_C25710 ((Vtx*) _vtx_C25710_path)
static const ALIGN_ASSET(2) char _vtx_C257D0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C257D0.vtx";
#define vtx_C257D0 ((Vtx*) _vtx_C257D0_path)
static const ALIGN_ASSET(2) char _vtx_C257F0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C257F0.vtx";
#define vtx_C257F0 ((Vtx*) _vtx_C257F0_path)
static const ALIGN_ASSET(2) char _vtx_C25900_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C25900.vtx";
#define vtx_C25900 ((Vtx*) _vtx_C25900_path)
static const ALIGN_ASSET(2) char _vtx_C25950_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C25950.vtx";
#define vtx_C25950 ((Vtx*) _vtx_C25950_path)
static const ALIGN_ASSET(2) char _vtx_C25A30_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C25A30.vtx";
#define vtx_C25A30 ((Vtx*) _vtx_C25A30_path)
static const ALIGN_ASSET(2) char _vtx_C25AB0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C25AB0.vtx";
#define vtx_C25AB0 ((Vtx*) _vtx_C25AB0_path)
static const ALIGN_ASSET(2) char _vtx_C25B30_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C25B30.vtx";
#define vtx_C25B30 ((Vtx*) _vtx_C25B30_path)
static const ALIGN_ASSET(2) char _vtx_C25BD0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C25BD0.vtx";
#define vtx_C25BD0 ((Vtx*) _vtx_C25BD0_path)
static const ALIGN_ASSET(2) char _vtx_C25C00_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C25C00.vtx";
#define vtx_C25C00 ((Vtx*) _vtx_C25C00_path)
static const ALIGN_ASSET(2) char _vtx_C25C20_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C25C20.vtx";
#define vtx_C25C20 ((Vtx*) _vtx_C25C20_path)
static const ALIGN_ASSET(2) char _vtx_C25C80_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C25C80.vtx";
#define vtx_C25C80 ((Vtx*) _vtx_C25C80_path)
static const ALIGN_ASSET(2) char _vtx_C25CF0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C25CF0.vtx";
#define vtx_C25CF0 ((Vtx*) _vtx_C25CF0_path)
static const ALIGN_ASSET(2) char _vtx_C25D30_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C25D30.vtx";
#define vtx_C25D30 ((Vtx*) _vtx_C25D30_path)
static const ALIGN_ASSET(2) char _vtx_C25DA0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C25DA0.vtx";
#define vtx_C25DA0 ((Vtx*) _vtx_C25DA0_path)
static const ALIGN_ASSET(2) char _vtx_C25DD0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C25DD0.vtx";
#define vtx_C25DD0 ((Vtx*) _vtx_C25DD0_path)
static const ALIGN_ASSET(2) char _vtx_C25EA0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C25EA0.vtx";
#define vtx_C25EA0 ((Vtx*) _vtx_C25EA0_path)
static const ALIGN_ASSET(2) char _vtx_C25F00_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C25F00.vtx";
#define vtx_C25F00 ((Vtx*) _vtx_C25F00_path)
static const ALIGN_ASSET(2) char _vtx_C25F90_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C25F90.vtx";
#define vtx_C25F90 ((Vtx*) _vtx_C25F90_path)
static const ALIGN_ASSET(2) char _vtx_C26040_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26040.vtx";
#define vtx_C26040 ((Vtx*) _vtx_C26040_path)
static const ALIGN_ASSET(2) char _vtx_C26090_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26090.vtx";
#define vtx_C26090 ((Vtx*) _vtx_C26090_path)
static const ALIGN_ASSET(2) char _vtx_C26130_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26130.vtx";
#define vtx_C26130 ((Vtx*) _vtx_C26130_path)
static const ALIGN_ASSET(2) char _vtx_C26250_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26250.vtx";
#define vtx_C26250 ((Vtx*) _vtx_C26250_path)
static const ALIGN_ASSET(2) char _vtx_C26290_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26290.vtx";
#define vtx_C26290 ((Vtx*) _vtx_C26290_path)
static const ALIGN_ASSET(2) char _vtx_C262D0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C262D0.vtx";
#define vtx_C262D0 ((Vtx*) _vtx_C262D0_path)
static const ALIGN_ASSET(2) char _vtx_C26310_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26310.vtx";
#define vtx_C26310 ((Vtx*) _vtx_C26310_path)
static const ALIGN_ASSET(2) char _vtx_C26350_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26350.vtx";
#define vtx_C26350 ((Vtx*) _vtx_C26350_path)
static const ALIGN_ASSET(2) char _vtx_C26390_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26390.vtx";
#define vtx_C26390 ((Vtx*) _vtx_C26390_path)
static const ALIGN_ASSET(2) char _vtx_C263D0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C263D0.vtx";
#define vtx_C263D0 ((Vtx*) _vtx_C263D0_path)
static const ALIGN_ASSET(2) char _vtx_C26410_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26410.vtx";
#define vtx_C26410 ((Vtx*) _vtx_C26410_path)
static const ALIGN_ASSET(2) char _vtx_C26450_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26450.vtx";
#define vtx_C26450 ((Vtx*) _vtx_C26450_path)
static const ALIGN_ASSET(2) char _vtx_C26490_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26490.vtx";
#define vtx_C26490 ((Vtx*) _vtx_C26490_path)
static const ALIGN_ASSET(2) char _vtx_C264D0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C264D0.vtx";
#define vtx_C264D0 ((Vtx*) _vtx_C264D0_path)
static const ALIGN_ASSET(2) char _vtx_C26510_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26510.vtx";
#define vtx_C26510 ((Vtx*) _vtx_C26510_path)
static const ALIGN_ASSET(2) char _vtx_C26550_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26550.vtx";
#define vtx_C26550 ((Vtx*) _vtx_C26550_path)
static const ALIGN_ASSET(2) char _vtx_C26590_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26590.vtx";
#define vtx_C26590 ((Vtx*) _vtx_C26590_path)
static const ALIGN_ASSET(2) char _vtx_C265D0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C265D0.vtx";
#define vtx_C265D0 ((Vtx*) _vtx_C265D0_path)
static const ALIGN_ASSET(2) char _vtx_C26610_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26610.vtx";
#define vtx_C26610 ((Vtx*) _vtx_C26610_path)
static const ALIGN_ASSET(2) char _vtx_C26650_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26650.vtx";
#define vtx_C26650 ((Vtx*) _vtx_C26650_path)
static const ALIGN_ASSET(2) char _vtx_C26690_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26690.vtx";
#define vtx_C26690 ((Vtx*) _vtx_C26690_path)
static const ALIGN_ASSET(2) char _vtx_C266D0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C266D0.vtx";
#define vtx_C266D0 ((Vtx*) _vtx_C266D0_path)
static const ALIGN_ASSET(2) char _vtx_C26710_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26710.vtx";
#define vtx_C26710 ((Vtx*) _vtx_C26710_path)
static const ALIGN_ASSET(2) char _vtx_C26750_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26750.vtx";
#define vtx_C26750 ((Vtx*) _vtx_C26750_path)
static const ALIGN_ASSET(2) char _vtx_C26890_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26890.vtx";
#define vtx_C26890 ((Vtx*) _vtx_C26890_path)
static const ALIGN_ASSET(2) char _vtx_C26A60_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26A60.vtx";
#define vtx_C26A60 ((Vtx*) _vtx_C26A60_path)
static const ALIGN_ASSET(2) char _vtx_C26AE0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26AE0.vtx";
#define vtx_C26AE0 ((Vtx*) _vtx_C26AE0_path)
static const ALIGN_ASSET(2) char _vtx_C26CC0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26CC0.vtx";
#define vtx_C26CC0 ((Vtx*) _vtx_C26CC0_path)
static const ALIGN_ASSET(2) char _vtx_C26EB0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26EB0.vtx";
#define vtx_C26EB0 ((Vtx*) _vtx_C26EB0_path)
static const ALIGN_ASSET(2) char _vtx_C26F40_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26F40.vtx";
#define vtx_C26F40 ((Vtx*) _vtx_C26F40_path)
static const ALIGN_ASSET(2) char _vtx_C26FB0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C26FB0.vtx";
#define vtx_C26FB0 ((Vtx*) _vtx_C26FB0_path)
static const ALIGN_ASSET(2) char _vtx_C27110_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C27110.vtx";
#define vtx_C27110 ((Vtx*) _vtx_C27110_path)
static const ALIGN_ASSET(2) char _vtx_C27180_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C27180.vtx";
#define vtx_C27180 ((Vtx*) _vtx_C27180_path)
static const ALIGN_ASSET(2) char _vtx_C27220_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C27220.vtx";
#define vtx_C27220 ((Vtx*) _vtx_C27220_path)
static const ALIGN_ASSET(2) char _vtx_C27300_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C27300.vtx";
#define vtx_C27300 ((Vtx*) _vtx_C27300_path)
static const ALIGN_ASSET(2) char _vtx_C273A0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C273A0.vtx";
#define vtx_C273A0 ((Vtx*) _vtx_C273A0_path)
static const ALIGN_ASSET(2) char _vtx_C27460_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C27460.vtx";
#define vtx_C27460 ((Vtx*) _vtx_C27460_path)
static const ALIGN_ASSET(2) char _vtx_C27580_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C27580.vtx";
#define vtx_C27580 ((Vtx*) _vtx_C27580_path)
static const ALIGN_ASSET(2) char _vtx_C27740_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C27740.vtx";
#define vtx_C27740 ((Vtx*) _vtx_C27740_path)
static const ALIGN_ASSET(2) char _vtx_C27770_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C27770.vtx";
#define vtx_C27770 ((Vtx*) _vtx_C27770_path)
static const ALIGN_ASSET(2) char _vtx_C27880_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C27880.vtx";
#define vtx_C27880 ((Vtx*) _vtx_C27880_path)
static const ALIGN_ASSET(2) char _vtx_C27A40_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C27A40.vtx";
#define vtx_C27A40 ((Vtx*) _vtx_C27A40_path)
static const ALIGN_ASSET(2) char _vtx_C27A70_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C27A70.vtx";
#define vtx_C27A70 ((Vtx*) _vtx_C27A70_path)
static const ALIGN_ASSET(2) char _vtx_C27B80_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C27B80.vtx";
#define vtx_C27B80 ((Vtx*) _vtx_C27B80_path)
static const ALIGN_ASSET(2) char _vtx_C27D60_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C27D60.vtx";
#define vtx_C27D60 ((Vtx*) _vtx_C27D60_path)
static const ALIGN_ASSET(2) char _vtx_C27F20_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C27F20.vtx";
#define vtx_C27F20 ((Vtx*) _vtx_C27F20_path)
static const ALIGN_ASSET(2) char _vtx_C27FC0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C27FC0.vtx";
#define vtx_C27FC0 ((Vtx*) _vtx_C27FC0_path)
static const ALIGN_ASSET(2) char _vtx_C27FE0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C27FE0.vtx";
#define vtx_C27FE0 ((Vtx*) _vtx_C27FE0_path)
static const ALIGN_ASSET(2) char _vtx_C28080_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C28080.vtx";
#define vtx_C28080 ((Vtx*) _vtx_C28080_path)
static const ALIGN_ASSET(2) char _vtx_C28110_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C28110.vtx";
#define vtx_C28110 ((Vtx*) _vtx_C28110_path)
static const ALIGN_ASSET(2) char _vtx_C28190_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C28190.vtx";
#define vtx_C28190 ((Vtx*) _vtx_C28190_path)
static const ALIGN_ASSET(2) char _vtx_C281B0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C281B0.vtx";
#define vtx_C281B0 ((Vtx*) _vtx_C281B0_path)
static const ALIGN_ASSET(2) char _vtx_C281E0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C281E0.vtx";
#define vtx_C281E0 ((Vtx*) _vtx_C281E0_path)
static const ALIGN_ASSET(2) char _vtx_C282D0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C282D0.vtx";
#define vtx_C282D0 ((Vtx*) _vtx_C282D0_path)
static const ALIGN_ASSET(2) char _vtx_C282F0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C282F0.vtx";
#define vtx_C282F0 ((Vtx*) _vtx_C282F0_path)
static const ALIGN_ASSET(2) char _vtx_C28310_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C28310.vtx";
#define vtx_C28310 ((Vtx*) _vtx_C28310_path)
static const ALIGN_ASSET(2) char _vtx_C28420_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C28420.vtx";
#define vtx_C28420 ((Vtx*) _vtx_C28420_path)
static const ALIGN_ASSET(2) char _vtx_C284F0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C284F0.vtx";
#define vtx_C284F0 ((Vtx*) _vtx_C284F0_path)
static const ALIGN_ASSET(2) char _vtx_C28550_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C28550.vtx";
#define vtx_C28550 ((Vtx*) _vtx_C28550_path)
static const ALIGN_ASSET(2) char _vtx_C28690_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C28690.vtx";
#define vtx_C28690 ((Vtx*) _vtx_C28690_path)
static const ALIGN_ASSET(2) char _vtx_C28720_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C28720.vtx";
#define vtx_C28720 ((Vtx*) _vtx_C28720_path)
static const ALIGN_ASSET(2) char _vtx_C287A0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C287A0.vtx";
#define vtx_C287A0 ((Vtx*) _vtx_C287A0_path)
static const ALIGN_ASSET(2) char _vtx_C28890_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C28890.vtx";
#define vtx_C28890 ((Vtx*) _vtx_C28890_path)
static const ALIGN_ASSET(2) char _vtx_C28970_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C28970.vtx";
#define vtx_C28970 ((Vtx*) _vtx_C28970_path)
static const ALIGN_ASSET(2) char _vtx_C28A70_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C28A70.vtx";
#define vtx_C28A70 ((Vtx*) _vtx_C28A70_path)
static const ALIGN_ASSET(2) char _vtx_C28BB0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C28BB0.vtx";
#define vtx_C28BB0 ((Vtx*) _vtx_C28BB0_path)
static const ALIGN_ASSET(2) char _vtx_C28D90_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C28D90.vtx";
#define vtx_C28D90 ((Vtx*) _vtx_C28D90_path)
static const ALIGN_ASSET(2) char _vtx_C28F70_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C28F70.vtx";
#define vtx_C28F70 ((Vtx*) _vtx_C28F70_path)
static const ALIGN_ASSET(2) char _vtx_C29150_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C29150.vtx";
#define vtx_C29150 ((Vtx*) _vtx_C29150_path)
static const ALIGN_ASSET(2) char _vtx_C29330_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C29330.vtx";
#define vtx_C29330 ((Vtx*) _vtx_C29330_path)
static const ALIGN_ASSET(2) char _vtx_C29470_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C29470.vtx";
#define vtx_C29470 ((Vtx*) _vtx_C29470_path)
static const ALIGN_ASSET(2) char _vtx_C294A0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C294A0.vtx";
#define vtx_C294A0 ((Vtx*) _vtx_C294A0_path)
static const ALIGN_ASSET(2) char _vtx_C294F0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C294F0.vtx";
#define vtx_C294F0 ((Vtx*) _vtx_C294F0_path)
static const ALIGN_ASSET(2) char _vtx_C29540_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C29540.vtx";
#define vtx_C29540 ((Vtx*) _vtx_C29540_path)
static const ALIGN_ASSET(2) char _vtx_C29570_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C29570.vtx";
#define vtx_C29570 ((Vtx*) _vtx_C29570_path)
static const ALIGN_ASSET(2) char _vtx_C295B0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C295B0.vtx";
#define vtx_C295B0 ((Vtx*) _vtx_C295B0_path)
static const ALIGN_ASSET(2) char _vtx_C29630_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C29630.vtx";
#define vtx_C29630 ((Vtx*) _vtx_C29630_path)
static const ALIGN_ASSET(2) char _vtx_C29650_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C29650.vtx";
#define vtx_C29650 ((Vtx*) _vtx_C29650_path)
static const ALIGN_ASSET(2) char _vtx_C296C0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C296C0.vtx";
#define vtx_C296C0 ((Vtx*) _vtx_C296C0_path)
static const ALIGN_ASSET(2) char _vtx_C29750_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C29750.vtx";
#define vtx_C29750 ((Vtx*) _vtx_C29750_path)
static const ALIGN_ASSET(2) char _vtx_C297F0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C297F0.vtx";
#define vtx_C297F0 ((Vtx*) _vtx_C297F0_path)
static const ALIGN_ASSET(2) char _vtx_C298E0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C298E0.vtx";
#define vtx_C298E0 ((Vtx*) _vtx_C298E0_path)
static const ALIGN_ASSET(2) char _vtx_C29A40_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C29A40.vtx";
#define vtx_C29A40 ((Vtx*) _vtx_C29A40_path)
static const ALIGN_ASSET(2) char _vtx_C29AB0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C29AB0.vtx";
#define vtx_C29AB0 ((Vtx*) _vtx_C29AB0_path)
static const ALIGN_ASSET(2) char _vtx_C29BB0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C29BB0.vtx";
#define vtx_C29BB0 ((Vtx*) _vtx_C29BB0_path)
static const ALIGN_ASSET(2) char _vtx_C29CD0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C29CD0.vtx";
#define vtx_C29CD0 ((Vtx*) _vtx_C29CD0_path)
static const ALIGN_ASSET(2) char _vtx_C29E00_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C29E00.vtx";
#define vtx_C29E00 ((Vtx*) _vtx_C29E00_path)
static const ALIGN_ASSET(2) char _vtx_C29F50_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C29F50.vtx";
#define vtx_C29F50 ((Vtx*) _vtx_C29F50_path)
static const ALIGN_ASSET(2) char _vtx_C2A080_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2A080.vtx";
#define vtx_C2A080 ((Vtx*) _vtx_C2A080_path)
static const ALIGN_ASSET(2) char _vtx_C2A180_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2A180.vtx";
#define vtx_C2A180 ((Vtx*) _vtx_C2A180_path)
static const ALIGN_ASSET(2) char _vtx_C2A2C0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2A2C0.vtx";
#define vtx_C2A2C0 ((Vtx*) _vtx_C2A2C0_path)
static const ALIGN_ASSET(2) char _vtx_C2A3C0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2A3C0.vtx";
#define vtx_C2A3C0 ((Vtx*) _vtx_C2A3C0_path)
static const ALIGN_ASSET(2) char _vtx_C2A540_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2A540.vtx";
#define vtx_C2A540 ((Vtx*) _vtx_C2A540_path)
static const ALIGN_ASSET(2) char _vtx_C2A700_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2A700.vtx";
#define vtx_C2A700 ((Vtx*) _vtx_C2A700_path)
static const ALIGN_ASSET(2) char _vtx_C2A740_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2A740.vtx";
#define vtx_C2A740 ((Vtx*) _vtx_C2A740_path)
static const ALIGN_ASSET(2) char _vtx_C2A790_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2A790.vtx";
#define vtx_C2A790 ((Vtx*) _vtx_C2A790_path)
static const ALIGN_ASSET(2) char _vtx_C2A8D0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2A8D0.vtx";
#define vtx_C2A8D0 ((Vtx*) _vtx_C2A8D0_path)
static const ALIGN_ASSET(2) char _vtx_C2AAB0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2AAB0.vtx";
#define vtx_C2AAB0 ((Vtx*) _vtx_C2AAB0_path)
static const ALIGN_ASSET(2) char _vtx_C2AC90_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2AC90.vtx";
#define vtx_C2AC90 ((Vtx*) _vtx_C2AC90_path)
static const ALIGN_ASSET(2) char _vtx_C2AD20_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2AD20.vtx";
#define vtx_C2AD20 ((Vtx*) _vtx_C2AD20_path)
static const ALIGN_ASSET(2) char _vtx_C2AD70_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2AD70.vtx";
#define vtx_C2AD70 ((Vtx*) _vtx_C2AD70_path)
static const ALIGN_ASSET(2) char _vtx_C2AE50_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2AE50.vtx";
#define vtx_C2AE50 ((Vtx*) _vtx_C2AE50_path)
static const ALIGN_ASSET(2) char _vtx_C2AE70_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2AE70.vtx";
#define vtx_C2AE70 ((Vtx*) _vtx_C2AE70_path)
static const ALIGN_ASSET(2) char _vtx_C2AEB0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2AEB0.vtx";
#define vtx_C2AEB0 ((Vtx*) _vtx_C2AEB0_path)
static const ALIGN_ASSET(2) char _vtx_C2AF60_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2AF60.vtx";
#define vtx_C2AF60 ((Vtx*) _vtx_C2AF60_path)
static const ALIGN_ASSET(2) char _vtx_C2AF80_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2AF80.vtx";
#define vtx_C2AF80 ((Vtx*) _vtx_C2AF80_path)
static const ALIGN_ASSET(2) char _vtx_C2B010_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2B010.vtx";
#define vtx_C2B010 ((Vtx*) _vtx_C2B010_path)
static const ALIGN_ASSET(2) char _vtx_C2B050_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2B050.vtx";
#define vtx_C2B050 ((Vtx*) _vtx_C2B050_path)
static const ALIGN_ASSET(2) char _vtx_C2B220_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2B220.vtx";
#define vtx_C2B220 ((Vtx*) _vtx_C2B220_path)
static const ALIGN_ASSET(2) char _vtx_C2B250_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2B250.vtx";
#define vtx_C2B250 ((Vtx*) _vtx_C2B250_path)
static const ALIGN_ASSET(2) char _vtx_C2B2D0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2B2D0.vtx";
#define vtx_C2B2D0 ((Vtx*) _vtx_C2B2D0_path)
static const ALIGN_ASSET(2) char _vtx_C2B340_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2B340.vtx";
#define vtx_C2B340 ((Vtx*) _vtx_C2B340_path)
static const ALIGN_ASSET(2) char _vtx_C2B3C0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2B3C0.vtx";
#define vtx_C2B3C0 ((Vtx*) _vtx_C2B3C0_path)
static const ALIGN_ASSET(2) char _vtx_C2B3E0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2B3E0.vtx";
#define vtx_C2B3E0 ((Vtx*) _vtx_C2B3E0_path)
static const ALIGN_ASSET(2) char _vtx_C2B410_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2B410.vtx";
#define vtx_C2B410 ((Vtx*) _vtx_C2B410_path)
static const ALIGN_ASSET(2) char _vtx_C2B560_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2B560.vtx";
#define vtx_C2B560 ((Vtx*) _vtx_C2B560_path)
static const ALIGN_ASSET(2) char _vtx_C2B6D0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2B6D0.vtx";
#define vtx_C2B6D0 ((Vtx*) _vtx_C2B6D0_path)
static const ALIGN_ASSET(2) char _vtx_C2B800_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2B800.vtx";
#define vtx_C2B800 ((Vtx*) _vtx_C2B800_path)
static const ALIGN_ASSET(2) char _vtx_C2B850_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2B850.vtx";
#define vtx_C2B850 ((Vtx*) _vtx_C2B850_path)
static const ALIGN_ASSET(2) char _vtx_C2B8E0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2B8E0.vtx";
#define vtx_C2B8E0 ((Vtx*) _vtx_C2B8E0_path)
static const ALIGN_ASSET(2) char _vtx_C2B9B0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2B9B0.vtx";
#define vtx_C2B9B0 ((Vtx*) _vtx_C2B9B0_path)
static const ALIGN_ASSET(2) char _vtx_C2BA50_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2BA50.vtx";
#define vtx_C2BA50 ((Vtx*) _vtx_C2BA50_path)
static const ALIGN_ASSET(2) char _vtx_C2BB50_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2BB50.vtx";
#define vtx_C2BB50 ((Vtx*) _vtx_C2BB50_path)
static const ALIGN_ASSET(2) char _vtx_C2BD50_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2BD50.vtx";
#define vtx_C2BD50 ((Vtx*) _vtx_C2BD50_path)
static const ALIGN_ASSET(2) char _vtx_C2BE50_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2BE50.vtx";
#define vtx_C2BE50 ((Vtx*) _vtx_C2BE50_path)
static const ALIGN_ASSET(2) char _vtx_C2BF50_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2BF50.vtx";
#define vtx_C2BF50 ((Vtx*) _vtx_C2BF50_path)
static const ALIGN_ASSET(2) char _vtx_C2BF60_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2BF60.vtx";
#define vtx_C2BF60 ((Vtx*) _vtx_C2BF60_path)
static const ALIGN_ASSET(2) char _vtx_C2BFD0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2BFD0.vtx";
#define vtx_C2BFD0 ((Vtx*) _vtx_C2BFD0_path)
static const ALIGN_ASSET(2) char _vtx_C2C080_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2C080.vtx";
#define vtx_C2C080 ((Vtx*) _vtx_C2C080_path)
static const ALIGN_ASSET(2) char _vtx_C2C0B0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2C0B0.vtx";
#define vtx_C2C0B0 ((Vtx*) _vtx_C2C0B0_path)
static const ALIGN_ASSET(2) char _vtx_C2C0F0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2C0F0.vtx";
#define vtx_C2C0F0 ((Vtx*) _vtx_C2C0F0_path)
static const ALIGN_ASSET(2) char _vtx_C2C130_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2C130.vtx";
#define vtx_C2C130 ((Vtx*) _vtx_C2C130_path)
static const ALIGN_ASSET(2) char _vtx_C2C1C0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2C1C0.vtx";
#define vtx_C2C1C0 ((Vtx*) _vtx_C2C1C0_path)
static const ALIGN_ASSET(2) char _vtx_C2C300_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2C300.vtx";
#define vtx_C2C300 ((Vtx*) _vtx_C2C300_path)
static const ALIGN_ASSET(2) char _vtx_C2C4E0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2C4E0.vtx";
#define vtx_C2C4E0 ((Vtx*) _vtx_C2C4E0_path)
static const ALIGN_ASSET(2) char _vtx_C2C6C0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2C6C0.vtx";
#define vtx_C2C6C0 ((Vtx*) _vtx_C2C6C0_path)
static const ALIGN_ASSET(2) char _vtx_C2C8A0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2C8A0.vtx";
#define vtx_C2C8A0 ((Vtx*) _vtx_C2C8A0_path)
static const ALIGN_ASSET(2) char _vtx_C2CA20_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2CA20.vtx";
#define vtx_C2CA20 ((Vtx*) _vtx_C2CA20_path)
static const ALIGN_ASSET(2) char _vtx_C2CBA0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2CBA0.vtx";
#define vtx_C2CBA0 ((Vtx*) _vtx_C2CBA0_path)
static const ALIGN_ASSET(2) char _vtx_C2CD20_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2CD20.vtx";
#define vtx_C2CD20 ((Vtx*) _vtx_C2CD20_path)
static const ALIGN_ASSET(2) char _vtx_C2CEA0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2CEA0.vtx";
#define vtx_C2CEA0 ((Vtx*) _vtx_C2CEA0_path)
static const ALIGN_ASSET(2) char _vtx_C2CED0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2CED0.vtx";
#define vtx_C2CED0 ((Vtx*) _vtx_C2CED0_path)
static const ALIGN_ASSET(2) char _vtx_C2CF00_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2CF00.vtx";
#define vtx_C2CF00 ((Vtx*) _vtx_C2CF00_path)
static const ALIGN_ASSET(2) char _vtx_C2CFC0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2CFC0.vtx";
#define vtx_C2CFC0 ((Vtx*) _vtx_C2CFC0_path)
static const ALIGN_ASSET(2) char _vtx_C2D140_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2D140.vtx";
#define vtx_C2D140 ((Vtx*) _vtx_C2D140_path)
static const ALIGN_ASSET(2) char _vtx_C2D170_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2D170.vtx";
#define vtx_C2D170 ((Vtx*) _vtx_C2D170_path)
static const ALIGN_ASSET(2) char _vtx_C2D1A0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2D1A0.vtx";
#define vtx_C2D1A0 ((Vtx*) _vtx_C2D1A0_path)
static const ALIGN_ASSET(2) char _vtx_C2D260_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2D260.vtx";
#define vtx_C2D260 ((Vtx*) _vtx_C2D260_path)
static const ALIGN_ASSET(2) char _vtx_C2D3E0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2D3E0.vtx";
#define vtx_C2D3E0 ((Vtx*) _vtx_C2D3E0_path)
static const ALIGN_ASSET(2) char _vtx_C2D410_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2D410.vtx";
#define vtx_C2D410 ((Vtx*) _vtx_C2D410_path)
static const ALIGN_ASSET(2) char _vtx_C2D440_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2D440.vtx";
#define vtx_C2D440 ((Vtx*) _vtx_C2D440_path)
static const ALIGN_ASSET(2) char _vtx_C2D500_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2D500.vtx";
#define vtx_C2D500 ((Vtx*) _vtx_C2D500_path)
static const ALIGN_ASSET(2) char _vtx_C2D560_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2D560.vtx";
#define vtx_C2D560 ((Vtx*) _vtx_C2D560_path)
static const ALIGN_ASSET(2) char _vtx_C2D5C0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2D5C0.vtx";
#define vtx_C2D5C0 ((Vtx*) _vtx_C2D5C0_path)
static const ALIGN_ASSET(2) char _vtx_C2D620_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2D620.vtx";
#define vtx_C2D620 ((Vtx*) _vtx_C2D620_path)
static const ALIGN_ASSET(2) char _vtx_C2D660_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2D660.vtx";
#define vtx_C2D660 ((Vtx*) _vtx_C2D660_path)
static const ALIGN_ASSET(2) char _vtx_C2D6A0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2D6A0.vtx";
#define vtx_C2D6A0 ((Vtx*) _vtx_C2D6A0_path)
static const ALIGN_ASSET(2) char _vtx_C2D6E0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2D6E0.vtx";
#define vtx_C2D6E0 ((Vtx*) _vtx_C2D6E0_path)
static const ALIGN_ASSET(2) char _vtx_C2D830_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2D830.vtx";
#define vtx_C2D830 ((Vtx*) _vtx_C2D830_path)
static const ALIGN_ASSET(2) char _vtx_C2D8F0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2D8F0.vtx";
#define vtx_C2D8F0 ((Vtx*) _vtx_C2D8F0_path)
static const ALIGN_ASSET(2) char _vtx_C2DA20_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2DA20.vtx";
#define vtx_C2DA20 ((Vtx*) _vtx_C2DA20_path)
static const ALIGN_ASSET(2) char _vtx_C2DBE0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2DBE0.vtx";
#define vtx_C2DBE0 ((Vtx*) _vtx_C2DBE0_path)
static const ALIGN_ASSET(2) char _vtx_C2DCB0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2DCB0.vtx";
#define vtx_C2DCB0 ((Vtx*) _vtx_C2DCB0_path)
static const ALIGN_ASSET(2) char _vtx_C2DD50_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2DD50.vtx";
#define vtx_C2DD50 ((Vtx*) _vtx_C2DD50_path)
static const ALIGN_ASSET(2) char _vtx_C2DD90_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2DD90.vtx";
#define vtx_C2DD90 ((Vtx*) _vtx_C2DD90_path)
static const ALIGN_ASSET(2) char _vtx_C2DEA0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2DEA0.vtx";
#define vtx_C2DEA0 ((Vtx*) _vtx_C2DEA0_path)
static const ALIGN_ASSET(2) char _vtx_C2DFC0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2DFC0.vtx";
#define vtx_C2DFC0 ((Vtx*) _vtx_C2DFC0_path)
static const ALIGN_ASSET(2) char _vtx_C2E020_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2E020.vtx";
#define vtx_C2E020 ((Vtx*) _vtx_C2E020_path)
static const ALIGN_ASSET(2) char _vtx_C2E1E0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2E1E0.vtx";
#define vtx_C2E1E0 ((Vtx*) _vtx_C2E1E0_path)
static const ALIGN_ASSET(2) char _vtx_C2E2B0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2E2B0.vtx";
#define vtx_C2E2B0 ((Vtx*) _vtx_C2E2B0_path)
static const ALIGN_ASSET(2) char _vtx_C2E360_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2E360.vtx";
#define vtx_C2E360 ((Vtx*) _vtx_C2E360_path)
static const ALIGN_ASSET(2) char _vtx_C2E390_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2E390.vtx";
#define vtx_C2E390 ((Vtx*) _vtx_C2E390_path)
static const ALIGN_ASSET(2) char _vtx_C2E4A0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2E4A0.vtx";
#define vtx_C2E4A0 ((Vtx*) _vtx_C2E4A0_path)
static const ALIGN_ASSET(2) char _vtx_C2E5D0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2E5D0.vtx";
#define vtx_C2E5D0 ((Vtx*) _vtx_C2E5D0_path)
static const ALIGN_ASSET(2) char _vtx_C2E620_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2E620.vtx";
#define vtx_C2E620 ((Vtx*) _vtx_C2E620_path)
static const ALIGN_ASSET(2) char _vtx_C2E7B0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2E7B0.vtx";
#define vtx_C2E7B0 ((Vtx*) _vtx_C2E7B0_path)
static const ALIGN_ASSET(2) char _vtx_C2E800_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2E800.vtx";
#define vtx_C2E800 ((Vtx*) _vtx_C2E800_path)
static const ALIGN_ASSET(2) char _vtx_C2E8C0_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2E8C0.vtx";
#define vtx_C2E8C0 ((Vtx*) _vtx_C2E8C0_path)
static const ALIGN_ASSET(2) char _vtx_C2E980_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2E980.vtx";
#define vtx_C2E980 ((Vtx*) _vtx_C2E980_path)
static const ALIGN_ASSET(2) char _vtx_C2EA60_path[] = "__OTR__misc/dgb_smash_bridges/vtx_C2EA60.vtx";
#define vtx_C2EA60 ((Vtx*) _vtx_C2EA60_path)
