#ifndef SAVE_TYPES_H
#define SAVE_TYPES_H

#define MAX_PARTNERS 12
#define MAX_KEYITEMS 32
#define MAX_BADGES 128
#define MAX_INVITEMS 10
#define MAX_STOREDITEMS 32
#define MAX_EQUIPPEDBADGES 64
#define MAX_PARTNERUNLOCKTIME 12
#define MAX_PARTNERUSEDTIME 12
#define MAX_ENEMYDEFEATFLAGINDEX 60
#define MAX_ENEMYDEFEATFLAGDATA 12
#define MAX_GLOBALFLAGS 64
#define MAX_GLOBALBYTES 512
#define MAX_AREAFLAGS 8
#define MAX_AREABYTES 16
#define MAX_UNUSED0F 9
#define MAX_UNK1304 124
#define MAX_FILENAME 8

#endif // SAVE_TYPES_H
