#!/usr/bin/env python3
"""
Extract shape asset offsets from Paper Mario 64 ROM asset table.
Generates shapes.yml for the torch asset extraction system.

Usage: python3 tools/extract-shape-offsets.py [baserom.z64] > assets/yaml/us/shapes.yml
"""

import struct
import sys
import os

# US version asset table location
ASSET_TABLE_ROM_START = 0x1E40000
ASSET_TABLE_HEADER_SIZE = 0x20
ASSET_TABLE_FIRST_ENTRY = ASSET_TABLE_ROM_START + ASSET_TABLE_HEADER_SIZE

# AssetHeader structure (0x1C bytes):
#   0x00: name[16] - null-terminated string
#   0x10: offset (u32) - relative to ASSET_TABLE_FIRST_ENTRY
#   0x14: compressedLength (u32)
#   0x18: decompressedLength (u32)
ASSET_ENTRY_SIZE = 0x1C


def parse_asset_table(rom_path):
    """Parse the ROM asset table and extract shape entries."""
    shapes = []

    with open(rom_path, 'rb') as f:
        f.seek(ASSET_TABLE_FIRST_ENTRY)

        while True:
            entry = f.read(ASSET_ENTRY_SIZE)
            if len(entry) < ASSET_ENTRY_SIZE:
                break

            # Parse name (null-terminated string, max 16 chars)
            name_bytes = entry[:16]
            null_idx = name_bytes.find(b'\x00')
            if null_idx != -1:
                name_bytes = name_bytes[:null_idx]

            try:
                name = name_bytes.decode('ascii')
            except UnicodeDecodeError:
                break

            if not name:
                break

            # Parse offsets and sizes (big-endian)
            offset, comp_len, decomp_len = struct.unpack('>III', entry[16:28])

            # Calculate absolute ROM offset
            abs_offset = ASSET_TABLE_FIRST_ENTRY + offset

            # Filter for shape files (end with _shape)
            if name.endswith('_shape'):
                shapes.append({
                    'name': name,
                    'offset': abs_offset,
                    'compressed_size': comp_len,
                    'decompressed_size': decomp_len
                })

    return shapes


def generate_yaml(shapes):
    """Generate YAML output for shapes."""
    print(":config:")
    print("  segments:")
    print("    - [0x01, 0x01000000]")
    print()
    print("# Map shape files extracted from ROM asset table")
    print("# Generated by tools/extract-shape-offsets.py")
    print()

    for shape in sorted(shapes, key=lambda x: x['name']):
        name = shape['name']
        offset = shape['offset']
        # Use the map name without _shape suffix as the path
        map_name = name.replace('_shape', '')

        print(f"# {name}: compressed={shape['compressed_size']}, decompressed={shape['decompressed_size']}")
        print(f"{name}:")
        print(f"  {{ type: PM64:SHAPE, offset: 0x{offset:X}, symbol: {name} }}")
        print()


def main():
    if len(sys.argv) > 1:
        rom_path = sys.argv[1]
    else:
        # Try common locations
        candidates = ['baserom.z64', '../baserom.z64', 'build/baserom.z64']
        rom_path = None
        for candidate in candidates:
            if os.path.exists(candidate):
                rom_path = candidate
                break

        if rom_path is None:
            print("Usage: python3 tools/extract-shape-offsets.py [baserom.z64]", file=sys.stderr)
            print("Error: Could not find baserom.z64", file=sys.stderr)
            sys.exit(1)

    if not os.path.exists(rom_path):
        print(f"Error: ROM file not found: {rom_path}", file=sys.stderr)
        sys.exit(1)

    shapes = parse_asset_table(rom_path)

    if not shapes:
        print("Error: No shape assets found in ROM", file=sys.stderr)
        sys.exit(1)

    print(f"# Found {len(shapes)} shape assets", file=sys.stderr)
    generate_yaml(shapes)


if __name__ == '__main__':
    main()
