#!/usr/bin/env python3
"""
Extract sprite asset offsets from Paper Mario 64 ROM.
Generates sprites.yml for the torch asset extraction system.

Usage: python3 tools/extract-sprite-offsets.py [baserom.z64] > assets/yaml/us/sprites.yml
"""

import struct
import sys
import os

# US version sprite data location
SPRITE_ROM_BASE = 0x1943000
SPRITE_DATA_HEADER_OFFSET = 0x1943010  # Base + 0x10 header

# Constants
NUM_PLAYER_SPRITES = 14
NUM_NPC_SPRITES = 234


def read_u32_be(rom, offset):
    """Read a big-endian u32 from the ROM."""
    rom.seek(offset)
    data = rom.read(4)
    return struct.unpack('>I', data)[0]


def parse_sprite_data_header(rom):
    """Read the 3-value sprite data header."""
    player_raster_offset = read_u32_be(rom, SPRITE_DATA_HEADER_OFFSET)
    player_sprite_offset = read_u32_be(rom, SPRITE_DATA_HEADER_OFFSET + 4)
    npc_sprite_offset = read_u32_be(rom, SPRITE_DATA_HEADER_OFFSET + 8)
    return player_raster_offset, player_sprite_offset, npc_sprite_offset


def parse_player_sprite_index(rom, player_sprite_base):
    """Parse the player sprite index (array of 15 u32 offsets for 14 sprites)."""
    sprites = []

    # Read 15 offsets (14 sprites + end marker)
    offsets = []
    for i in range(NUM_PLAYER_SPRITES + 1):
        offset = read_u32_be(rom, player_sprite_base + i * 4)
        offsets.append(offset)

    # Calculate sprite entries
    for i in range(NUM_PLAYER_SPRITES):
        start_offset = offsets[i]
        end_offset = offsets[i + 1]
        size = end_offset - start_offset
        abs_offset = player_sprite_base + start_offset

        sprites.append({
            'index': i,
            'offset': abs_offset,
            'size': size
        })

    return sprites


def parse_npc_sprite_index(rom, npc_sprite_base):
    """Parse the NPC sprite index (array of 8-byte entries: start_offset, end_offset)."""
    sprites = []

    for i in range(NUM_NPC_SPRITES):
        entry_offset = npc_sprite_base + i * 8
        start_offset = read_u32_be(rom, entry_offset)
        end_offset = read_u32_be(rom, entry_offset + 4)

        size = end_offset - start_offset
        abs_offset = npc_sprite_base + start_offset

        sprites.append({
            'index': i,
            'offset': abs_offset,
            'size': size
        })

    return sprites


def generate_yaml(player_sprites, npc_sprites, player_sprite_base, npc_sprite_base):
    """Generate YAML output for sprites."""
    print(":config:")
    print("  segments:")
    print("    - [0x01, 0x01000000]")
    print()
    print("# Sprite assets extracted from ROM")
    print("# Generated by tools/extract-sprite-offsets.py")
    print()

    # Sprite data headers
    print("# === Sprite Data Headers ===")
    print("sprite_data_header:")
    print("  { type: BLOB, offset: 0x1943010, size: 0xC, symbol: gSpriteDataHeader }")
    print()
    print("player_raster_header:")
    print("  { type: BLOB, offset: 0x1943020, size: 0xC, symbol: gPlayerRasterHeader }")
    print()
    print("player_raster_sets:")
    print("  { type: BLOB, offset: 0x1943030, size: 0x38, symbol: gPlayerRasterSets }")
    print()
    print("player_raster_load_descriptors:")
    print("  { type: BLOB, offset: 0x1943068, size: 0xB38, symbol: gPlayerRasterLoadDescriptors }")
    print()
    print("player_raster_image_data:")
    print("  { type: BLOB, offset: 0x1943BA0, size: 0x9CDD0, symbol: gPlayerRasterImageData }")
    print()

    # Player sprite index
    index_size = (NUM_PLAYER_SPRITES + 1) * 4  # 15 entries * 4 bytes
    print("# === Player Sprite Index ===")
    print("player_sprite_index:")
    print(f"  {{ type: BLOB, offset: 0x{player_sprite_base:X}, size: 0x{index_size:X}, symbol: gPlayerSpriteIndex }}")
    print()

    # Player sprites
    print(f"# === Player Sprites ({NUM_PLAYER_SPRITES} total) ===")
    for sprite in player_sprites:
        idx = sprite['index']
        offset = sprite['offset']
        size = sprite['size']
        print(f"# player_sprite_{idx}: size=0x{size:X}")
        print(f"player_sprite_{idx}:")
        print(f"  {{ type: PM64:SPRITE, offset: 0x{offset:X}, symbol: gPlayerSprite{idx} }}")
        print()

    # NPC sprite index
    npc_index_size = NUM_NPC_SPRITES * 8  # 234 entries * 8 bytes
    print("# === NPC Sprite Index ===")
    print("npc_sprite_index:")
    print(f"  {{ type: BLOB, offset: 0x{npc_sprite_base:X}, size: 0x{npc_index_size:X}, symbol: gNpcSpriteIndex }}")
    print()

    # NPC sprites
    print(f"# === NPC Sprites ({NUM_NPC_SPRITES} total) ===")
    for sprite in npc_sprites:
        idx = sprite['index']
        offset = sprite['offset']
        size = sprite['size']
        print(f"# npc_sprite_{idx:03d}: size=0x{size:X}")
        print(f"npc_sprite_{idx:03d}:")
        print(f"  {{ type: PM64:SPRITE, offset: 0x{offset:X}, symbol: gNpcSprite{idx:03d} }}")
        print()


def main():
    if len(sys.argv) > 1:
        rom_path = sys.argv[1]
    else:
        # Try common locations
        candidates = ['baserom.z64', '../baserom.z64', 'build/baserom.z64']
        rom_path = None
        for candidate in candidates:
            if os.path.exists(candidate):
                rom_path = candidate
                break

        if rom_path is None:
            print("Usage: python3 tools/extract-sprite-offsets.py [baserom.z64]", file=sys.stderr)
            print("Error: Could not find baserom.z64", file=sys.stderr)
            sys.exit(1)

    if not os.path.exists(rom_path):
        print(f"Error: ROM file not found: {rom_path}", file=sys.stderr)
        sys.exit(1)

    with open(rom_path, 'rb') as rom:
        # Parse sprite data header
        player_raster_offset, player_sprite_offset, npc_sprite_offset = parse_sprite_data_header(rom)

        # Calculate absolute base addresses
        player_sprite_base = SPRITE_DATA_HEADER_OFFSET + player_sprite_offset
        npc_sprite_base = SPRITE_DATA_HEADER_OFFSET + npc_sprite_offset

        print(f"# Sprite Data Header:", file=sys.stderr)
        print(f"#   Player raster offset: 0x{player_raster_offset:X}", file=sys.stderr)
        print(f"#   Player sprite offset: 0x{player_sprite_offset:X} (base: 0x{player_sprite_base:X})", file=sys.stderr)
        print(f"#   NPC sprite offset: 0x{npc_sprite_offset:X} (base: 0x{npc_sprite_base:X})", file=sys.stderr)

        # Parse sprite indices
        player_sprites = parse_player_sprite_index(rom, player_sprite_base)
        npc_sprites = parse_npc_sprite_index(rom, npc_sprite_base)

        print(f"# Found {len(player_sprites)} player sprites and {len(npc_sprites)} NPC sprites", file=sys.stderr)

        # Generate YAML
        generate_yaml(player_sprites, npc_sprites, player_sprite_base, npc_sprite_base)


if __name__ == '__main__':
    main()
